facebook:
  client:
    clientId: clientId
    clientSecret: clientSecret
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

github:
  client:
    clientId: clientId
    clientSecret: clientSecret
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

# This client is the equivalent of the facebook.client* and github.client* that we need for the external authentication.
# With the external providers we had to register and get a client ID and a secret to use in our app.
# In this case we are providing our own equivalent of the same feature, so we need (at least one) client for it to work.
security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'

server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:jbcp_clientauth.p12
    key-store-password: changeit
    key-alias: jbcpclient

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:h2:mem:datasource;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      enabled: true
      path: /h2-console
